### ISSUE TITLE
close ticket loader img is too big

### ISSUE THREAD

**Issue by stefanorosanelli** [bedita/tickets#37]
See screenshot on ticket closing....

![close-ticket](https://cloud.githubusercontent.com/assets/2122280/10785322/a719e686-7d63-11e5-99d0-cc5f336bed0f.png)

**Comment by xho** [comment]
Changed just javascript behavior on CSS class toggle. (all this javascript events should be reviewed, but it's not useful now, let's do better in BEdita 4)
